In [9]:
import pandas as pd

In [ ]:
df = pd.read_csv('../../data/life_expectancy.csv')
df = df[['Sex', 'TIME_PERIOD', 'OBS_VALUE']]
df

In [46]:
df_retairement = pd.read_csv('../../data/retairement_age.csv')

In [48]:
df_retairement

    year  total  hommes  femmes
0   1991   62.1    61.6    64.0
1   1992   62.2    61.7    63.9
2   1993   60.8    60.5    63.6
3   1994   61.8    61.5    63.7
4   1995   62.0    61.6    64.0
5   1996   61.8    61.3    63.7
6   1997   61.8    61.4    63.7
7   1998   61.9    61.5    63.7
8   1999   62.3    61.9    63.9
9   2000   62.4    62.0    63.6
10  2001   62.5    62.2    63.5
11  2002   62.2    61.8    63.4
12  2003   62.0    61.6    63.4
13  2004   61.7    61.3    63.1
14  2005   61.6    61.2    63.0
15  2006   61.5    61.0    62.7
16  2007   61.5    61.1    62.4
17  2008   61.4    61.1    62.2
18  2009   61.4    61.1    62.1
19  2010   61.3    60.9    62.1
20  2011   61.4    61.1    62.1
21  2012   61.7    61.4    62.2
22  2013   61.6    61.3    62.3
23  2014   61.6    61.3    62.1
24  2015   61.6    61.3    62.2
25  2016   61.6    61.3    62.0
26  2017   61.8    61.6    62.1
27  2018   61.7    61.4    62.1
28  2019   61.7    61.5    62.1
29  2020   61.7    61.5    62.0
30  2021   61.6    61.4    61.9
31  2022   61.6    61.4    61.8
32  2023   61.4    61.2    61.6

In [ ]:
result = {}
for year in df['TIME_PERIOD'].unique():
    result[year] = {
        'life_m': df[(df['TIME_PERIOD'] == year) & (df['Sex'] == 'Men')]['OBS_VALUE'].iloc[0],
        'life_f': df[(df['TIME_PERIOD'] == year) & (df['Sex'] == 'Women')]['OBS_VALUE'].iloc[0],
        'retirement_age': df_retairement[df_retairement['year'] == year]['total'].iloc[0] if not df_retairement[df_retairement['year'] == year].empty else None

    }

In [57]:
result

{1947: {'life_m': 61.7, 'life_f': 65.8, 'retirement_age': None},
 1973: {'life_m': 67.3, 'life_f': 74.5, 'retirement_age': None},
 1981: {'life_m': 70.0, 'life_f': 76.7, 'retirement_age': None},
 1986: {'life_m': 70.6, 'life_f': 77.9, 'retirement_age': None},
 1991: {'life_m': 72.6, 'life_f': 79.1, 'retirement_age': 62.1},
 1996: {'life_m': 73.53, 'life_f': 79.62, 'retirement_age': 61.8},
 2001: {'life_m': 74.8, 'life_f': 81.01, 'retirement_age': 62.5},
 2006: {'life_m': 76.6, 'life_f': 81.8, 'retirement_age': 61.5},
 2011: {'life_m': 78.6, 'life_f': 83.4, 'retirement_age': 61.4},
 2012: {'life_m': 78.9, 'life_f': 83.4, 'retirement_age': 61.7},
 2013: {'life_m': 79.3, 'life_f': 84.0, 'retirement_age': 61.6},
 2014: {'life_m': 79.6, 'life_f': 84.2, 'retirement_age': 61.6},
 2015: {'life_m': 79.7, 'life_f': 84.6, 'retirement_age': 61.6},
 2016: {'life_m': 79.923495566085,
  'life_f': 84.3840984479308,
  'retirement_age': 61.6},
 2017: {'life_m': 79.9524716357209,
  'life_f': 84.4912017777248,
  'retirement_age': 61.8},
 2018: {'life_m': 80.005847767741,
  'life_f': 84.4732194649691,
  'retirement_age': 61.7},
 2019: {'life_m': 80.1, 'life_f': 84.6, 'retirement_age': 61.7},
 2020: {'life_m': 80.3, 'life_f': 84.8, 'retirement_age': 61.7},
 2021: {'life_m': 80.4927845133518,
  'life_f': 84.8252331364547,
  'retirement_age': 61.6},
 2022: {'life_m': 80.9802509079452,
  'life_f': 84.9818539956985,
  'retirement_age': 61.6},
 2023: {'life_m': 81.2025234247845,
  'life_f': 85.2574178319497,
  'retirement_age': 61.4}}

In [5]:
data = response.json()

In [47]:
df_retairement

    year  total  hommes  femmes
0   1991   62.1    61.6    64.0
1   1992   62.2    61.7    63.9
2   1993   60.8    60.5    63.6
3   1994   61.8    61.5    63.7
4   1995   62.0    61.6    64.0
5   1996   61.8    61.3    63.7
6   1997   61.8    61.4    63.7
7   1998   61.9    61.5    63.7
8   1999   62.3    61.9    63.9
9   2000   62.4    62.0    63.6
10  2001   62.5    62.2    63.5
11  2002   62.2    61.8    63.4
12  2003   62.0    61.6    63.4
13  2004   61.7    61.3    63.1
14  2005   61.6    61.2    63.0
15  2006   61.5    61.0    62.7
16  2007   61.5    61.1    62.4
17  2008   61.4    61.1    62.2
18  2009   61.4    61.1    62.1
19  2010   61.3    60.9    62.1
20  2011   61.4    61.1    62.1
21  2012   61.7    61.4    62.2
22  2013   61.6    61.3    62.3
23  2014   61.6    61.3    62.1
24  2015   61.6    61.3    62.2
25  2016   61.6    61.3    62.0
26  2017   61.8    61.6    62.1
27  2018   61.7    61.4    62.1
28  2019   61.7    61.5    62.1
29  2020   61.7    61.5    62.0
30  2021   61.6    61.4    61.9
31  2022   61.6    61.4    61.8
32  2023   61.4    61.2    61.6

In [7]:
data['data']

{'dataSets': [{'structure': 0,
   'action': 'Information',
   'links': [{'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.DataStructure=LU1:DSD_B2209(1.0)',
     'rel': 'DataStructure'}],
   'annotations': [0, 1, 2, 3, 4, 5],
   'attributes': [0, None],
   'observations': {'0:0:0:0': [24.7, None, None, 0, None, None, 0],
    '0:0:0:1': [27.5, None, None, 0, None, None, 0],
    '0:0:0:2': [29.2, None, None, 0, None, None, 0],
    '0:0:0:3': [30.1, None, None, 0, None, None, 0],
    '0:0:0:4': [31.5, None, None, 0, None, None, 0],
    '0:0:0:5': [31.72, None, None, 0, None, None, 0],
    '0:0:0:6': [32.76, None, None, 0, None, None, 0],
    '0:0:0:7': [33.3, None, None, 0, None, None, 0],
    '0:0:0:8': [34.4, None, None, 0, None, None, 0],
    '0:0:0:9': [34.5, None, None, 0, None, None, 0],
    '0:0:0:10': [35, None, None, 0, None, None, 0],
    '0:0:0:11': [35.1, None, None, 0, None, None, 0],
    '0:0:0:12': [35.5, None, None, 0, None, None, 0],
    '0:0:0:13': [35.2469594298352, None, None, 0, None, None, 0],
    '0:0:0:14': [35.3978936945743, None, None, 0, None, None, 0],
    '0:0:0:15': [35.2973845839332, None, None, 0, None, None, 0],
    '0:0:0:16': [35.4, None, None, 0, None, None, 0],
    '0:0:0:17': [35.7, None, None, 0, None, None, 0],
    '0:0:0:18': [35.6704195091901, None, None, 0, None, None, 0],
    '0:0:0:19': [35.8523454674671, None, None, 0, None, None, 0],
    '0:0:0:20': [36.0660041927136, None, None, 0, None, None, 0],
    '1:1:0:0': [61.7, None, None, 1, None, None, 0],
    '1:1:0:1': [67.3, None, None, 1, None, None, 0],
    '1:1:0:2': [70, None, None, 1, None, None, 0],
    '1:1:0:3': [70.6, None, None, 1, None, None, 0],
    '1:1:0:4': [72.6, None, None, 1, None, None, 0],
    '1:1:0:5': [73.53, None, None, 1, None, None, 0],
    '1:1:0:6': [74.8, None, None, 1, None, None, 0],
    '1:1:0:7': [76.6, None, None, 1, None, None, 0],
    '1:1:0:8': [78.6, None, None, 1, None, None, 0],
    '1:1:0:9': [78.9, None, None, 1, None, None, 0],
    '1:1:0:10': [79.3, None, None, 1, None, None, 0],
    '1:1:0:11': [79.6, None, None, 1, None, None, 0],
    '1:1:0:12': [79.7, None, None, 1, None, None, 0],
    '1:1:0:13': [79.923495566085, None, None, 1, None, None, 0],
    '1:1:0:14': [79.9524716357209, None, None, 1, None, None, 0],
    '1:1:0:15': [80.005847767741, None, None, 1, None, None, 0],
    '1:1:0:16': [80.1, None, None, 1, None, None, 0],
    '1:1:0:17': [80.3, None, None, 1, None, None, 0],
    '1:1:0:18': [80.4927845133518, None, None, 1, None, None, 0],
    '1:1:0:19': [80.9802509079452, None, None, 1, None, None, 0],
    '1:1:0:20': [81.2025234247845, None, None, 1, None, None, 0],
    '0:2:0:0': [10.3, None, None, 2, None, None, 0],
    '0:2:0:1': [11.9, None, None, 2, None, None, 0],
    '0:2:0:2': [13, None, None, 2, None, None, 0],
    '0:2:0:3': [13.3, None, None, 2, None, None, 0],
    '0:2:0:4': [14.9, None, None, 2, None, None, 0],
    '0:2:0:5': [15.31, None, None, 2, None, None, 0],
    '0:2:0:6': [15.8, None, None, 2, None, None, 0],
    '0:2:0:7': [16, None, None, 2, None, None, 0],
    '0:2:0:8': [17, None, None, 2, None, None, 0],
    '0:2:0:9': [17, None, None, 2, None, None, 0],
    '0:2:0:10': [17.4, None, None, 2, None, None, 0],
    '0:2:0:11': [17.4, None, None, 2, None, None, 0],
    '0:2:0:12': [17.6, None, None, 2, None, None, 0],
    '0:2:0:13': [17.4216571630489, None, None, 2, None, None, 0],
    '0:2:0:14': [17.5569604387553, None, None, 2, None, None, 0],
    '0:2:0:15': [17.5554015326296, None, None, 2, None, None, 0],
    '0:2:0:16': [17.6, None, None, 2, None, None, 0],
    '0:2:0:17': [18.8, None, None, 2, None, None, 0],
    '0:2:0:18': [17.7228105320724, None, None, 2, None, None, 0],
    '0:2:0:19': [17.8763611683771, None, None, 2, None, None, 0],
    '0:2:0:20': [18.0305159660646, None, None, 2, None, None, 0],
    '1:3:0:0': [48, None, None, 3, None, None, 0],
    '1:3:0:1': [49.5, None, None, 3, None, None, 0],
    '1:3:0:2': [50.9, None, None, 3, None, None, 0],
    '1:3:0:3': [51.9, None, None, 3, None, None, 0],
    '1:3:0:4': [54, None, None, 3, None, None, 0],
    '1:3:0:5': [54.26, None, None, 3, None, None, 0],
    '1:3:0:6': [55.7, None, None, 3, None, None, 0],
    '1:3:0:7': [57.1, None, None, 3, None, None, 0],
    '1:3:0:8': [58.9, None, None, 3, None, None, 0],
    '1:3:0:9': [59.3, None, None, 3, None, None, 0],
    '1:3:0:10': [59.7, None, None, 3, None, None, 0],
    '1:3:0:11': [60, None, None, 3, None, None, 0],
    '1:3:0:12': [60.1, None, None, 3, None, None, 0],
    '1:3:0:13': [60.3210462543012, None, None, 3, None, None, 0],
    '1:3:0:14': [60.2883588314435, None, None, 3, None, None, 0],
    '1:3:0:15': [60.3931305490435, None, None, 3, None, None, 0],
    '1:3:0:16': [60.4, None, None, 3, None, None, 0],
    '1:3:0:17': [60.6, None, None, 3, None, None, 0],
    '1:3:0:18': [60.8233388908301, None, None, 3, None, None, 0],
    '1:3:0:19': [61.3124692841007, None, None, 3, None, None, 0],
    '1:3:0:20': [61.6206739955587, None, None, 3, None, None, 0],
    '1:4:0:0': [30.3, None, None, 4, None, None, 0],
    '1:4:0:1': [31.1, None, None, 4, None, None, 0],
    '1:4:0:2': [32.4, None, None, 4, None, None, 0],
    '1:4:0:3': [33.2, None, None, 4, None, None, 0],
    '1:4:0:4': [35.3, None, None, 4, None, None, 0],
    '1:4:0:5': [35.43, None, None, 4, None, None, 0],
    '1:4:0:6': [36.9, None, None, 4, None, None, 0],
    '1:4:0:7': [38, None, None, 4, None, None, 0],
    '1:4:0:8': [39.6, None, None, 4, None, None, 0],
    '1:4:0:9': [39.9, None, None, 4, None, None, 0],
    '1:4:0:10': [40.3, None, None, 4, None, None, 0],
    '1:4:0:11': [40.6, None, None, 4, None, None, 0],
    '1:4:0:12': [40.7, None, None, 4, None, None, 0],
    '1:4:0:13': [40.7933112134335, None, None, 4, None, None, 0],
    '1:4:0:14': [40.7721083497723, None, None, 4, None, None, 0],
    '1:4:0:15': [40.951284931418, None, None, 4, None, None, 0],
    '1:4:0:16': [41, None, None, 4, None, None, 0],
    '1:4:0:17': [41.1, None, None, 4, None, None, 0],
    '1:4:0:18': [41.2552304948107, None, None, 4, None, None, 0],
    '1:4:0:19': [41.7450826602232, None, None, 4, None, None, 0],
    '1:4:0:20': [42.0732479596628, None, None, 4, None, None, 0],
    '0:4:0:0': [33.4, None, None, 4, None, None, 0],
    '0:4:0:1': [36.5, None, None, 4, None, None, 0],
    '0:4:0:2': [38.4, None, None, 4, None, None, 0],
    '0:4:0:3': [39.4, None, None, 4, None, None, 0],
    '0:4:0:4': [40.8, None, None, 4, None, None, 0],
    '0:4:0:5': [41.07, None, None, 4, None, None, 0],
    '0:4:0:6': [42.15, None, None, 4, None, None, 0],
    '0:4:0:7': [42.7, None, None, 4, None, None, 0],
    '0:4:0:8': [44, None, None, 4, None, None, 0],
    '0:4:0:9': [44.1, None, None, 4, None, None, 0],
    '0:4:0:10': [44.6, None, None, 4, None, None, 0],
    '0:4:0:11': [44.7, None, None, 4, None, None, 0],
    '0:4:0:12': [45.1, None, None, 4, None, None, 0],
    '0:4:0:13': [44.8117690208263, None, None, 4, None, None, 0],
    '0:4:0:14': [45.0073638320547, None, None, 4, None, None, 0],
    '0:4:0:15': [44.9450781205133, None, None, 4, None, None, 0],
    '0:4:0:16': [45.1, None, None, 4, None, None, 0],
    '0:4:0:17': [45.3, None, None, 4, None, None, 0],
    '0:4:0:18': [45.3540509409961, None, None, 4, None, None, 0],
    '0:4:0:19': [45.5266043937864, None, None, 4, None, None, 0],
    '0:4:0:20': [45.7324052923359, None, None, 4, None, None, 0],
    '0:5:0:0': [16.9, None, None, 5, None, None, 0],
    '0:5:0:1': [19.2, None, None, 5, None, None, 0],
    '0:5:0:2': [20.7, None, None, 5, None, None, 0],
    '0:5:0:3': [21.3, None, None, 5, None, None, 0],
    '0:5:0:4': [22.7, None, None, 5, None, None, 0],
    '0:5:0:5': [22.99, None, None, 5, None, None, 0],
    '0:5:0:6': [23.8, None, None, 5, None, None, 0],
    '0:5:0:7': [24.3, None, None, 5, None, None, 0],
    '0:5:0:8': [25.4, None, None, 5, None, None, 0],
    '0:5:0:9': [25.4, None, None, 5, None, None, 0],
    '0:5:0:10': [25.8, None, None, 5, None, None, 0],
    '0:5:0:11': [25.9, None, None, 5, None, None, 0],
    '0:5:0:12': [26.2, None, None, 5, None, None, 0],
    '0:5:0:13': [25.9521338991626, None, None, 5, None, None, 0],
    '0:5:0:14': [26.1355056775772, None, None, 5, None, None, 0],
    '0:5:0:15': [26.1007428679515, None, None, 5, None, None, 0],
    '0:5:0:16': [26.2, None, None, 5, None, None, 0],
    '0:5:0:17': [26.4, None, None, 5, None, None, 0],
    '0:5:0:18': [26.3370440464284, None, None, 5, None, None, 0],
    '0:5:0:19': [26.5175821472437, None, None, 5, None, None, 0],
    '0:5:0:20': [26.7022298920675, None, None, 5, None, None, 0],
    '0:1:0:0': [65.8, None, None, 1, None, None, 0],
    '0:1:0:1': [74.5, None, None, 1, None, None, 0],
    '0:1:0:2': [76.7, None, None, 1, None, None, 0],
    '0:1:0:3': [77.9, None, None, 1, None, None, 0],
    '0:1:0:4': [79.1, None, None, 1, None, None, 0],
    '0:1:0:5': [79.62, None, None, 1, None, None, 0],
    '0:1:0:6': [81.01, None, None, 1, None, None, 0],
    '0:1:0:7': [81.8, None, None, 1, None, None, 0],
    '0:1:0:8': [83.4, None, None, 1, None, None, 0],
    '0:1:0:9': [83.4, None, None, 1, None, None, 0],
    '0:1:0:10': [84, None, None, 1, None, None, 0],
    '0:1:0:11': [84.2, None, None, 1, None, None, 0],
    '0:1:0:12': [84.6, None, None, 1, None, None, 0],
    '0:1:0:13': [84.3840984479308, None, None, 1, None, None, 0],
    '0:1:0:14': [84.4912017777248, None, None, 1, None, None, 0],
    '0:1:0:15': [84.4732194649691, None, None, 1, None, None, 0],
    '0:1:0:16': [84.6, None, None, 1, None, None, 0],
    '0:1:0:17': [84.8, None, None, 1, None, None, 0],
    '0:1:0:18': [84.8252331364547, None, None, 1, None, None, 0],
    '0:1:0:19': [84.9818539956985, None, None, 1, None, None, 0],
    '0:1:0:20': [85.2574178319497, None, None, 1, None, None, 0],
    '1:0:0:0': [22.2, None, None, 0, None, None, 0],
    '1:0:0:1': [22.4, None, None, 0, None, None, 0],
    '1:0:0:2': [23.6, None, None, 0, None, None, 0],
    '1:0:0:3': [24.2, None, None, 0, None, None, 0],
    '1:0:0:4': [26.4, None, None, 0, None, None, 0],
    '1:0:0:5': [26.55, None, None, 0, None, None, 0],
    '1:0:0:6': [27.84, None, None, 0, None, None, 0],
    '1:0:0:7': [28.8, None, None, 0, None, None, 0],
    '1:0:0:8': [30.2, None, None, 0, None, None, 0],
    '1:0:0:9': [30.5, None, None, 0, None, None, 0],
    '1:0:0:10': [30.8, None, None, 0, None, None, 0],
    '1:0:0:11': [31.1, None, None, 0, None, None, 0],
    '1:0:0:12': [31.2, None, None, 0, None, None, 0],
    '1:0:0:13': [31.3549966487821, None, None, 0, None, None, 0],
    '1:0:0:14': [31.3270261559441, None, None, 0, None, None, 0],
    '1:0:0:15': [31.4751657585929, None, None, 0, None, None, 0],
    '1:0:0:16': [31.4, None, None, 0, None, None, 0],
    '1:0:0:17': [31.6, None, None, 0, None, None, 0],
    '1:0:0:18': [31.7440380314844, None, None, 0, None, None, 0],
    '1:0:0:19': [32.2212840294086, None, None, 0, None, None, 0],
    '1:0:0:20': [32.5229189083324, None, None, 0, None, None, 0],
    '1:5:0:0': [14.1, None, None, 5, None, None, 0],
    '1:5:0:1': [15, None, None, 5, None, None, 0],
    '1:5:0:2': [16, None, None, 5, None, None, 0],
    '1:5:0:3': [16.4, None, None, 5, None, None, 0],
    '1:5:0:4': [18.4, None, None, 5, None, None, 0],
    '1:5:0:5': [18.56, None, None, 5, None, None, 0],
    '1:5:0:6': [19.5, None, None, 5, None, None, 0],
    '1:5:0:7': [20.4, None, None, 5, None, None, 0],
    '1:5:0:8': [21.6, None, None, 5, None, None, 0],
    '1:5:0:9': [21.9, None, None, 5, None, None, 0],
    '1:5:0:10': [22.3, None, None, 5, None, None, 0],
    '1:5:0:11': [22.5, None, None, 5, None, None, 0],
    '1:5:0:12': [22.5, None, None, 5, None, None, 0],
    '1:5:0:13': [22.5347693435129, None, None, 5, None, None, 0],
    '1:5:0:14': [22.4953370417879, None, None, 5, None, None, 0],
    '1:5:0:15': [22.5805147114003, None, None, 5, None, None, 0],
    '1:5:0:16': [22.6, None, None, 5, None, None, 0],
    '1:5:0:17': [22.8, None, None, 5, None, None, 0],
    '1:5:0:18': [22.8806230786144, None, None, 5, None, None, 0],
    '1:5:0:19': [23.3090007814742, None, None, 5, None, None, 0],
    '1:5:0:20': [23.5630753544236, None, None, 5, None, None, 0],
    '1:2:0:0': [9.3, None, None, 2, None, None, 0],
    '1:2:0:1': [9.5, None, None, 2, None, None, 0],
    '1:2:0:2': [9.9, None, None, 2, None, None, 0],
    '1:2:0:3': [10.1, None, None, 2, None, None, 0],
    '1:2:0:4': [11.9, None, None, 2, None, None, 0],
    '1:2:0:5': [11.88, None, None, 2, None, None, 0],
    '1:2:0:6': [12.5, None, None, 2, None, None, 0],
    '1:2:0:7': [13.1, None, None, 2, None, None, 0],
    '1:2:0:8': [14, None, None, 2, None, None, 0],
    '1:2:0:9': [14.3, None, None, 2, None, None, 0],
    '1:2:0:10': [14.6, None, None, 2, None, None, 0],
    '1:2:0:11': [14.7, None, None, 2, None, None, 0],
    '1:2:0:12': [14.7, None, None, 2, None, None, 0],
    '1:2:0:13': [14.8184785514204, None, None, 2, None, None, 0],
    '1:2:0:14': [14.8210024218888, None, None, 2, None, None, 0],
    '1:2:0:15': [14.9200401762905, None, None, 2, None, None, 0],
    '1:2:0:16': [14.8, None, None, 2, None, None, 0],
    '1:2:0:17': [15, None, None, 2, None, None, 0],
    '1:2:0:18': [15.0699291176975, None, None, 2, None, None, 0],
    '1:2:0:19': [15.389462356936, None, None, 2, None, None, 0],
    '1:2:0:20': [15.6093650163138, None, None, 2, None, None, 0],
    '0:3:0:0': [51.5, None, None, 3, None, None, 0],
    '0:3:0:1': [55.8, None, None, 3, None, None, 0],
    '0:3:0:2': [57.4, None, None, 3, None, None, 0],
    '0:3:0:3': [58.8, None, None, 3, None, None, 0],
    '0:3:0:4': [60, None, None, 3, None, None, 0],
    '0:3:0:5': [60.39, None, None, 3, None, None, 0],
    '0:3:0:6': [61.62, None, None, 3, None, None, 0],
    '0:3:0:7': [62.2, None, None, 3, None, None, 0],
    '0:3:0:8': [63.6, None, None, 3, None, None, 0],
    '0:3:0:9': [63.7, None, None, 3, None, None, 0],
    '0:3:0:10': [64.2, None, None, 3, None, None, 0],
    '0:3:0:11': [64.4, None, None, 3, None, None, 0],
    '0:3:0:12': [64.9, None, None, 3, None, None, 0],
    '0:3:0:13': [64.5921801295366, None, None, 3, None, None, 0],
    '0:3:0:14': [64.7190124662084, None, None, 3, None, None, 0],
    '0:3:0:15': [64.6798825096922, None, None, 3, None, None, 0],
    '0:3:0:16': [64.9, None, None, 3, None, None, 0],
    '0:3:0:17': [65.1, None, None, 3, None, None, 0],
    '0:3:0:18': [65.0907638293696, None, None, 3, None, None, 0],
    '0:3:0:19': [65.3026087313604, None, None, 3, None, None, 0],
    '0:3:0:20': [65.505940330144, None, None, 3, None, None, 0]}}],
 'structures': [{'name': 'Life expectancy at different ages',
   'names': {'en': 'Life expectancy at different ages'},
   'description': 'Publication date: 13/05/2025 - Periodicity: annual - Author: STATEC - Category: Population and employment - Population - Keywords: mortality, life expectancy, demography',
   'descriptions': {'en': 'Publication date: 13/05/2025 - Periodicity: annual - Author: STATEC - Category: Population and employment - Population - Keywords: mortality, life expectancy, demography'},
   'dimensions': {'dataSet': [],
    'series': [],
    'observation': [{'id': 'SEX',
      'name': 'Sex',
      'names': {'en': 'Sex'},
      'keyPosition': 0,
      'roles': ['SEX'],
      'values': [{'id': 'S02',
        'order': 1,
        'name': 'Women',
        'names': {'en': 'Women'}},
       {'id': 'S01', 'order': 0, 'name': 'Men', 'names': {'en': 'Men'}}]},
     {'id': 'AGE',
      'name': 'Age',
      'names': {'en': 'Age'},
      'keyPosition': 1,
      'roles': ['AGE'],
      'values': [{'id': 'SL04',
        'order': 3,
        'name': '50',
        'names': {'en': '50'}},
       {'id': 'SL01', 'order': 0, 'name': '0', 'names': {'en': '0'}},
       {'id': 'SL06', 'order': 5, 'name': '70', 'names': {'en': '70'}},
       {'id': 'SL02', 'order': 1, 'name': '20', 'names': {'en': '20'}},
       {'id': 'SL03', 'order': 2, 'name': '40', 'names': {'en': '40'}},
       {'id': 'SL05', 'order': 4, 'name': '60', 'names': {'en': '60'}}]},
     {'id': 'FREQ',
      'name': 'Frequency',
      'names': {'en': 'Frequency'},
      'keyPosition': 2,
      'roles': ['FREQ'],
      'values': [{'id': 'A',
        'order': 0,
        'name': 'Annual',
        'names': {'en': 'Annual'}}]},
     {'id': 'TIME_PERIOD',
      'name': 'Time period',
      'names': {'en': 'Time period'},
      'keyPosition': 3,
      'roles': ['TIME_PERIOD'],
      'values': [{'start': '1947-01-01T00:00:00',
        'end': '1947-12-31T23:59:59',
        'id': '1947',
        'name': '1947',
        'names': {'en': '1947'}},
       {'start': '1973-01-01T00:00:00',
        'end': '1973-12-31T23:59:59',
        'id': '1973',
        'name': '1973',
        'names': {'en': '1973'}},
       {'start': '1981-01-01T00:00:00',
        'end': '1981-12-31T23:59:59',
        'id': '1981',
        'name': '1981',
        'names': {'en': '1981'}},
       {'start': '1986-01-01T00:00:00',
        'end': '1986-12-31T23:59:59',
        'id': '1986',
        'name': '1986',
        'names': {'en': '1986'}},
       {'start': '1991-01-01T00:00:00',
        'end': '1991-12-31T23:59:59',
        'id': '1991',
        'name': '1991',
        'names': {'en': '1991'}},
       {'start': '1996-01-01T00:00:00',
        'end': '1996-12-31T23:59:59',
        'id': '1996',
        'name': '1996',
        'names': {'en': '1996'}},
       {'start': '2001-01-01T00:00:00',
        'end': '2001-12-31T23:59:59',
        'id': '2001',
        'name': '2001',
        'names': {'en': '2001'}},
       {'start': '2006-01-01T00:00:00',
        'end': '2006-12-31T23:59:59',
        'id': '2006',
        'name': '2006',
        'names': {'en': '2006'}},
       {'start': '2011-01-01T00:00:00',
        'end': '2011-12-31T23:59:59',
        'id': '2011',
        'name': '2011',
        'names': {'en': '2011'}},
       {'start': '2012-01-01T00:00:00',
        'end': '2012-12-31T23:59:59',
        'id': '2012',
        'name': '2012',
        'names': {'en': '2012'}},
       {'start': '2013-01-01T00:00:00',
        'end': '2013-12-31T23:59:59',
        'id': '2013',
        'name': '2013',
        'names': {'en': '2013'}},
       {'start': '2014-01-01T00:00:00',
        'end': '2014-12-31T23:59:59',
        'id': '2014',
        'name': '2014',
        'names': {'en': '2014'}},
       {'start': '2015-01-01T00:00:00',
        'end': '2015-12-31T23:59:59',
        'id': '2015',
        'name': '2015',
        'names': {'en': '2015'}},
       {'start': '2016-01-01T00:00:00',
        'end': '2016-12-31T23:59:59',
        'id': '2016',
        'name': '2016',
        'names': {'en': '2016'}},
       {'start': '2017-01-01T00:00:00',
        'end': '2017-12-31T23:59:59',
        'id': '2017',
        'name': '2017',
        'names': {'en': '2017'}},
       {'start': '2018-01-01T00:00:00',
        'end': '2018-12-31T23:59:59',
        'id': '2018',
        'name': '2018',
        'names': {'en': '2018'}},
       {'start': '2019-01-01T00:00:00',
        'end': '2019-12-31T23:59:59',
        'id': '2019',
        'name': '2019',
        'names': {'en': '2019'}},
       {'start': '2020-01-01T00:00:00',
        'end': '2020-12-31T23:59:59',
        'id': '2020',
        'name': '2020',
        'names': {'en': '2020'}},
       {'start': '2021-01-01T00:00:00',
        'end': '2021-12-31T23:59:59',
        'id': '2021',
        'name': '2021',
        'names': {'en': '2021'}},
       {'start': '2022-01-01T00:00:00',
        'end': '2022-12-31T23:59:59',
        'id': '2022',
        'name': '2022',
        'names': {'en': '2022'}},
       {'start': '2023-01-01T00:00:00',
        'end': '2023-12-31T23:59:59',
        'id': '2023',
        'name': '2023',
        'names': {'en': '2023'}}]}]},
   'attributes': {'dataSet': [{'id': 'NOTE_YEAR_1',
      'name': 'Note year 1',
      'names': {'en': 'Note year 1'},
      'roles': ['NOTE_YEAR_1'],
      'relationship': {'dataflow': {}},